CREATE DATABASE IF NOT EXISTS SSP DEFAULT CHARSET utf8 COLLATE utf8_general_ci;

USE ssp;

CREATE TABLE IF NOT EXISTS T_USER(
   ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
   `NAME` VARCHAR(20) NOT NULL UNIQUE,
   `PASSWORD` VARCHAR(100) NOT NULL,
	 LOCKED TINYINT DEFAULT 0 NOT NULL,
   PRIMARY KEY ( ID )
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS T_USER_INFO(
   GENDER CHAR(1),
	 BIRTHDAY DATE,
	 SELF_INTRODUCTION VARCHAR(50),
	 REGISTRATION_TIME DATETIME NOT NULL DEFAULT NOW(),
	 AVATAR_URL VARCHAR(500) NOT NULL DEFAULT '/resource/avatar/default.jpg',
	 USER_ID INT UNSIGNED NOT NULL,
   PRIMARY KEY ( USER_ID ),
	 FOREIGN KEY ( USER_ID ) REFERENCES T_USER( ID )
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS T_SHARE(
   ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
   CONTENT VARCHAR(300) NOT NULL,
TIME DATETIME DEFAULT NOW(),
   STATE VARCHAR( 30 ) NOT NULL,
   LIKENUM INT UNSIGNED DEFAULT 0,
   COLLECTNUM INT UNSIGNED DEFAULT 0,
   COMMENTNUM INT UNSIGNED DEFAULT 0,
   USER_ID INT UNSIGNED NOT NULL,
   PRIMARY KEY ( ID ),
	 FOREIGN KEY ( USER_ID ) REFERENCES T_USER( ID )
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS T_COMMENT(
   ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
   CONTENT VARCHAR(300) NOT NULL,
	 TIME DATETIME DEFAULT NOW(),
   USER_ID INT UNSIGNED NOT NULL,
	 SHARE_ID INT UNSIGNED NOT NULL,
   PRIMARY KEY ( ID ),
	 FOREIGN KEY ( USER_ID ) REFERENCES T_USER( ID ),
	 FOREIGN KEY ( SHARE_ID ) REFERENCES T_SHARE( ID )
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS T_REPLY(
   ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
   CONTENT VARCHAR(300) NOT NULL,
	 TIME DATETIME DEFAULT NOW(),
   SEND_USER_ID INT UNSIGNED NOT NULL,
	 ACCEPT_USER_ID INT UNSIGNED NOT NULL,
	 COMMENT_ID INT UNSIGNED NOT NULL,
   PRIMARY KEY ( ID ),
	 FOREIGN KEY ( SEND_USER_ID ) REFERENCES T_USER( ID ),
	 FOREIGN KEY ( ACCEPT_USER_ID ) REFERENCES T_USER( ID ),
	 FOREIGN KEY ( COMMENT_ID ) REFERENCES T_COMMENT( ID )
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS T_SENSITIVE_KEYWORD(
   ID INT UNSIGNED AUTO_INCREMENT,
   KEYWORD VARCHAR(10) NOT NULL UNIQUE,
   PRIMARY KEY ( ID )
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS T_PICTURE(
   ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
   URL VARCHAR(500) NOT NULL,
   SHARE_ID INT UNSIGNED NOT NULL,
   PRIMARY KEY ( ID ),
   FOREIGN KEY ( SHARE_ID ) REFERENCES T_SHARE( ID )
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS T_FOLLOW(
   FROM_USER_ID INT UNSIGNED NOT NULL,
   TO_USER_ID INT UNSIGNED NOT NULL,
	 FOLLOW_TIME DATETIME DEFAULT NOW(),
   PRIMARY KEY ( FROM_USER_ID,TO_USER_ID ),
	 FOREIGN KEY ( FROM_USER_ID ) REFERENCES T_USER( ID ),
	 FOREIGN KEY ( TO_USER_ID ) REFERENCES T_USER( ID )
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS T_LIKE(
   USER_ID INT UNSIGNED NOT NULL,
   SHARE_ID INT UNSIGNED NOT NULL,
	 LIKE_TIME DATETIME DEFAULT NOW(),
   PRIMARY KEY ( USER_ID,SHARE_ID ),
	 FOREIGN KEY ( USER_ID ) REFERENCES T_USER( ID ),
	 FOREIGN KEY ( SHARE_ID ) REFERENCES T_SHARE( ID )
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS T_COLLECT(
   USER_ID INT UNSIGNED NOT NULL,
   SHARE_ID INT UNSIGNED NOT NULL,
	 COLLECT_TIME DATETIME DEFAULT NOW(),
   PRIMARY KEY ( USER_ID,SHARE_ID ),
	 FOREIGN KEY ( USER_ID ) REFERENCES T_USER( ID ),
	 FOREIGN KEY ( SHARE_ID ) REFERENCES T_SHARE( ID )
)ENGINE=InnoDB DEFAULT CHARSET=utf8;